-----------------------------------------------------------------------------
-- CM_ACADEMIC_SESSION_T
-----------------------------------------------------------------------------

CREATE TABLE CM_ACADEMIC_SESSION_T
(
    ACADEMIC_SESSION_ID 	INT 	NOT NULL,
	VERSION INT 			NOT 	NULL,
	LAST_MODIFIED_BY 		VARCHAR(99),
	LAST_MODIFIED_DATE		DATE,
	CREATED_BY				VARCHAR(99),
	CREATED_DATE			DATE,
	ENTERPRISE_ID			VARCHAR(99) NOT NULL,
    TITLE					VARCHAR(99) NOT NULL,
    DESCRIPTION				VARCHAR(99) NOT NULL,
    START_DATE				DATE,
    END_DATE				DATE
);

ALTER TABLE CM_ACADEMIC_SESSION_T
       ADD  ( PRIMARY KEY (ENTERPRISE_ID) ) ;
       
       
CREATE SEQUENCE CM_ACADEMIC_SESSION_S;


-- Generated by hibernate schema export tag 2.4 QA 010
-- create table CM_ACADEMIC_SESSION_T 
--       (
--        ACADEMIC_SESSION_ID bigint generated by default as identity (start with 1), 
--        VERSION integer not null, 
--        LAST_MODIFIED_BY varchar(255), 
--        LAST_MODIFIED_DATE date, 
--        CREATED_BY varchar(255), 
--        CREATED_DATE date, 
--        ENTERPRISE_ID varchar(255) not null, 
--        TITLE varchar(255) not null, 
--        DESCRIPTION varchar(255) not null, 
--        START_DATE date, 
--        END_DATE date, 
--        primary key (ACADEMIC_SESSION_ID), unique (ENTERPRISE_ID));

-- alter table CM_MEMBER_CONTAINER_T add constraint FKD96A9BC6661E50E9 foreign key (ACADEMIC_SESSION) references CM_ACADEMIC_SESSION_T;


-- This data works with the first definition.  The first alter table doesn't work ??.

-- insert into cm_academic_session_t values(0, 1, 'admin', '2007-04-10', 'admin', '2007-04-10', 'WINTER 2007', 'WINTER_2007', 'WINTER 2007', '2007-01-01', '2007-04-30');
-- insert into cm_academic_session_t values(1, 1, 'admin', '2007-04-10', 'admin', '2007-04-10', 'SPRING 2007', 'SPRING_2007', 'SPRING 2007', '2007-05-01', '2007-08-01');


