CREATE TABLE SSQ_ANSWER
(
       ID varchar2(99) PRIMARY KEY NOT NULL,
       ANSWER varchar2(255),
       ANSWER_STRING varchar2(255),
       FILL_IN_BLANK decimal(1),
       ORDER_NUM decimal(10),
       QUESTION_ID varchar2(99)
)
;
CREATE TABLE SSQ_QUESTION
(
       ID varchar2(99) PRIMARY KEY NOT NULL,
       QUESTION varchar2(255),
       REQUIRED decimal(1),
       MULTIPLE_ANSWERS decimal(1),
       ORDER_NUM decimal(10),
       SITETYPE_ID varchar2(99)
)
;
CREATE TABLE SSQ_SITETYPE_QUESTIONS
(
       ID varchar2(99) PRIMARY KEY NOT NULL,
       SITE_TYPE varchar2(255),
       INSTRUCTION varchar2(255),
       URL varchar2(255),
       URL_LABEL varchar2(255),
       URL_TARGET varchar2(255)
)
;
CREATE TABLE SSQ_USER_ANSWER
(
       ID varchar2(99) PRIMARY KEY NOT NULL,
       SITE_ID varchar2(255),
       USER_ID varchar2(255),
       ANSWER_STRING varchar2(255),
       ANSWER_ID varchar2(255),
       QUESTION_ID varchar2(255)
)
;
ALTER TABLE SSQ_ANSWER
ADD CONSTRAINT SSQ_ANSWER_FK
FOREIGN KEY (QUESTION_ID)
REFERENCES SSQ_QUESTION(ID)

;
CREATE UNIQUE INDEX SSQ_ANSWER_UNIQUE ON SSQ_ANSWER(ID)
;
ALTER TABLE SSQ_QUESTION
ADD CONSTRAINT SSQ_QUESTION_FK
FOREIGN KEY (SITETYPE_ID)
REFERENCES SSQ_SITETYPE_QUESTIONS(ID)

;
CREATE UNIQUE INDEX SSQ_QUESTION_IDX ON SSQ_QUESTION(ID)

CREATE UNIQUE INDEX SSQ_SITETYPE_QUESTIONS_IDX ON SSQ_SITETYPE_QUESTIONS(ID)
;
CREATE UNIQUE INDEX SSQ_USER_ANSWER_IDX ON SSQ_USER_ANSWER(ID)
;
